blank_issues_enabled: true
contact_links:
  - name: Telegram Support Bot
    url: https://t.me/SkyVilleBot
    about: Contattaci qui per ricevere di supporto
  - name: Discord Server
    url: https://go.skyville.it/discord
    about: Entra nel nostro server discord
